---

- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Ensure apache is running (and enable it at boot)
  service: name=httpd state=started enabled=yes

- name: Install Php
  yum:
     name:
     - php
     - php-gd
     - php-pear
     - php-mysql
     - mysql57
     - MySQL-python27
     state: present


# MyBB Installation check | if config.php exists
- stat: path={{ httpDir }}/inc/config.php
  ignore_errors: true
  register: mybb_install

- block:
  - name: COPY | Copy all mybb under apache root dir
    unarchive:
      src: mybb_ready.tar.gz 
      dest: "{{ httpDir }}"

  - name: COPY | Copy database dump file
    copy:
      src: mybb_dump.sql
      dest: /tmp

  - name: INSTALL | Create a new database 
    mysql_db:
      name: "{{ rdsdb }}"
      login_host: "{{ rdshost }}"
      login_user: "{{ rdsuser }}"
      login_password: "{{ rdspass }}"
      state: present


  - name: INSTALL | Restore database
    mysql_db:
      name: my_db
      login_host: "{{ rdshost }}"
      login_password: "{{ rdspass }}"
      login_user: "{{ rdsuser }}"
      state: import
      target: /tmp/mysql_dump.sql

  - name: INSTALL | Ensure config file exists
    file: path={{ httpDir }}/inc/config.php
    notify:
       - restart apache

  - name: INSTALL | Set proper permissions on config folders
    file: path={{ httpDir }}{{ item }} mode=0777 recurse=yes
    with_items:
      - cache/
      - uploads/
      - admin/backups/

  - name: INSTALL | Set owner for all mybb files
    file:
      path: "{{ httpDir }}"
      owner: "apache"
      group: "apache"
      recurse: yes
    notify:
      - restart apache

  - name: INSTALL | Remove install folder
    file: path={{ httpDir }}install state=absent

  - name: INSTALL | Set proper permissions to config files (for security)
    file: path={{ httpDir }}inc/{{ item }}  mode=0644
    with_items:
      - config.php
      - settings.php


#  Only execute the above task block if we haven't already installed mybb 
#  when: mybb_install.stat.exists == False
 
