---

vpc_stack: VPC
subnet_stack: Subnets
igw_stack: IgwNatRouting
sec_stack: SecuritySettings
mon_stack: MonitoringServer
auto_stack: WebServers
rds_stack: DBServers
jump_stack: BastionServer 
dyn_stack: DynamoDB
mgt_stack: ManagementServer
